# Generated by Django 5.0.6 on 2024-07-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_file_postfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='post/files'),
        ),
        migrations.DeleteModel(
            name='PostFile',
        ),
    ]
